repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
      exclude: '^core/cube/|\bdocstrings\.h$'
    - id: trailing-whitespace
      exclude: '^core/cube/|\bdocstrings\.h$'
    - id: check-json
    - id: check-xml
    - id: pretty-format-json
- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
    - id: black
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
    - id: clang-format
      args: [ "--style=file:./.clang-format", -i]
      exclude: '^core/cube/|\bdocstrings\.h$'
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
  - id: cmake-lint
