variables:
  NPROC: 16

airbot-aloha:
  stage: build
  image: registry.qiuzhi.tech/airbot-play/arm-control:develop
  script:
    - sed -i 's|http://archive.ubuntu.com/|http://mirrors.ustc.edu.cn/|' /etc/apt/sources.list
    - apt update && DEBIAN_FRONTEND=noninteractive TZ=Asia/Shanghai apt install -y libopencv-* python3 python3-pip
    - cd examples/airbot_aloha && mkdir build && cd build && cmake .. && make -j $NPROC && cpack -G DEB
    - mkdir $CI_PROJECT_DIR/packages && mv ../*.deb $CI_PROJECT_DIR/packages
  artifacts:
    paths:
      - packages/
    expire_in: 1 week

airbot-aloha-upload:
  stage: release
  needs:
    - job: airbot-aloha
      artifacts: true
  image: curlimages/curl:latest
  # rules:
  #   - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_PROTECTED == "true"
  script:
    - export DEB_FILE=$(ls packages/ | grep deb)
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file packages/${DEB_FILE} \
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/airbot-aloha/${CI_COMMIT_REF_NAME}/${DEB_FILE}
