variables:
  ROS_CI_REGISTRY_IMAGE: registry.qiuzhi.tech/airbot-play/ros-interface

python:
  stage: build
  image: ${CI_REGISTRY}/airbot-play/arm-control:v2.7.2
  script:
    - sed -i 's|http://archive.ubuntu.com/|http://mirrors.tuna.tsinghua.edu.cn/|' /etc/apt/sources.list
    - apt update && DEBIAN_FRONTEND=noninteractive TZ=Asia/Shanghai apt install -y python3 python3-wheel python3-pip
    - cd python && python3 setup.py bdist_wheel
    - mkdir -p $CI_PROJECT_DIR/packages && mv dist/*.whl $CI_PROJECT_DIR/packages
  artifacts:
    paths:
      - packages/
    expire_in: 1 week

python-upload:
  stage: release
  needs:
    - job: python
      artifacts: true
  image: curlimages/curl:latest
  # rules:
  #   - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_PROTECTED == "true"
  script:
    - export WHL_FILE=$(ls packages/ | grep whl)
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file packages/${WHL_FILE} \
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/python-sdk/${CI_COMMIT_REF_NAME}/${WHL_FILE}
