variables:
  ROS_CI_REGISTRY_IMAGE: registry.qiuzhi.tech/airbot-play/ros-interface

python:
  stage: build
  image: ${CI_REGISTRY}/airbot-play/arm-control:develop
  script:
    - sed -i 's|http://archive.ubuntu.com/|http://mirrors.tuna.tsinghua.edu.cn/|' /etc/apt/sources.list
    - apt update && DEBIAN_FRONTEND=noninteractive TZ=Asia/Shanghai apt install -y python3 python3-wheel python3-pip
    - cd python && python3 setup.py bdist_wheel
    - mkdir -p $CI_PROJECT_DIR/packages && mv dist/*.whl $CI_PROJECT_DIR/packages
  artifacts:
    paths:
      - packages/
    expire_in: 1 week
