variables:
  GIT_SUBMODULE_STRATEGY: recursive

python-doc:
  stage: build
  image: ${CI_REGISTRY}/airbot-play/arm-control:develop
  script:
    - cd python
    - apt-get update && apt-get install -y doxygen zip python3-pip ca-certificates
    - if [ -n "$CI_COMMIT_TAG" ]; then DEPLOY_REF=$CI_COMMIT_TAG; else DEPLOY_REF=latest; fi
    - mkdir -p packages/ && zip -qr python.zip python/ && mv python.zip packages/
    - pip3 install -r docs/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
    - python3 -m pybind11_mkdoc -o src/doc.hpp -I/usr/include/eigen3 -std=c++17 /usr/local/include/airbot/command/command_base.hpp /usr/local/include/airbot/modules/motors/motor_driver.hpp
    - pip install .
    - cd docs && make html && cd build/html && git init
    - git config --global user.email "project_112_bot_916e14ffbe0fea32f0cb67cfb3521647@noreply.example.com"
    - git config --global user.name "project_112_bot_916e14ffbe0fea32f0cb67cfb3521647"
    - git add .
    - git checkout -b doc/${DEPLOY_REF}/python
    - git commit -m "doc push" --no-verify || true
    - git remote add origin "https://oauth2:$DOC_ACCESS_TOKEN@git.qiuzhi.tech/${CI_PROJECT_PATH}"
    - git push --force --set-upstream origin doc/${DEPLOY_REF}/python

  artifacts:
    paths:
      - packages/
    expire_in: 1 week

python-upload:
  stage: release
  needs:
    - job: python-doc
      artifacts: true
  image: curlimages/curl:latest
  # rules:
  #   - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_PROTECTED == "true"
  script:
    - export WHL_FILE=$(ls packages/ | grep whl)
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file packages/${WHL_FILE} \
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/python-sdk/${CI_COMMIT_REF_NAME}/${WHL_FILE}
