default:
  tags:
    - linux/amd64

stages:
  - prepare
  - test
  - build

variables:
  DOCKER_HOST: tcp://dockerhost:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_BUILDKIT: '1'
  GIT_SUBMODULE_STRATEGY: none
  CI_REGISTRY: registry.qiuzhi.tech
  CI_REGISTRY_IMAGE: registry.qiuzhi.tech/airbot-play/arm-control-daemon

prepare_submodule:
  stage: prepare
  image: ubuntu:20.04
  script:
    - sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirrors.tuna.tsinghua.edu.cn/ubuntu/|' /etc/apt/sources.list
    - apt-get update && apt-get install -y git-core
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@".insteadOf "https://"
    - git submodule sync --recursive && git submodule update --init --recursive

docker-build:
  rules:
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_PROTECTED == "true"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - cache/
  needs: 
    - job: prepare_submodule
  stage: build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind-rootless
      alias: dockerhost
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  before_script:
    - docker info
  script:
    - docker context create builder
    - docker buildx create builder --use --driver docker-container --driver-opt image=moby/buildkit:master --driver-opt network=host
    - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $CI_REGISTRY
    - docker buildx build --platform linux/amd64,linux/arm64 -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --cache-from type=local,src=cache/ --cache-to type=local,dest=cache/ --build-arg NPROC=48 --build-arg REF=${CI_COMMIT_REF_NAME} . --push
